### The Basics of Numpy
* Homogeneous multidimensional arrays
* Dimensions are called axis
* Python array.array is not same as numpy.array

In [2]:
import numpy as np
# create a 1D array of size 5
arr = np.array([1,2,3,4,5])
print("Dimension of the array is ", arr.ndim) 
# This is a tuple of integers indicating the size of the array in each dimension
print("Shape of the array is ", arr.shape)
print("Size of the array is ", arr.size)
print("Type of the array is ", arr.dtype)
print("Item size of the array is ", arr.itemsize)
      

Dimension of the array is  1
Shape of the array is  (5,)
Size of the array is  5
Type of the array is  int64
Item size of the array is  8


In [3]:
# creating 2D array of size 4x5
arr1 = np.arange(20).reshape(4,5)
print("Dimension of the array is ", arr1.ndim)
print("Shape of the array is ", arr1.shape)
print("Size of the array is ", arr1.size)
print("Type of the array is ", arr1.dtype)
print("Item size of the array is ", arr1.itemsize)

Dimension of the array is  2
Shape of the array is  (4, 5)
Size of the array is  20
Type of the array is  int64
Item size of the array is  8


### Creation of array


In [4]:
# creating an array from a list/tuple of values
list1 = [1,2,3,4,5]
tuple1 = (1,2,3,4,5)
list_to_array = np.array(list1)
tuple_to_array = np.array(tuple1)
print("list1 is a ", type(list1))
print("tuple1 is a ", type(tuple1))
print("list_to_array is a ", type(list_to_array))
print("tuple_to_array is a ", type(tuple_to_array))
print(list_to_array)
print(tuple_to_array)


list1 is a  <class 'list'>
tuple1 is a  <class 'tuple'>
list_to_array is a  <class 'numpy.ndarray'>
tuple_to_array is a  <class 'numpy.ndarray'>
[1 2 3 4 5]
[1 2 3 4 5]


In [5]:
# creating an array  of any dimension
arr_1d = np.array([1,2,3,4,5])
arr_2d = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr_1d)
print(arr_2d)

[1 2 3 4 5]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [6]:
# creating an array with complex data types
complex = np.array([1+1j,2+2j,3+3j,4+4j,5+5j])
print(complex.dtype)
# complex2 = np.array([[1,2],[3,4,5]], dtype=complex)

complex128


In [7]:
# random array of size 5x5
arr_random = np.random.rand(5,5)
arr_random_int = np.random.randint(0,10,(5,5))
print(arr_random)
print(arr_random_int)

[[0.34518204 0.57664109 0.62849259 0.30282804 0.99743367]
 [0.40576134 0.51754846 0.35830551 0.74552922 0.18213492]
 [0.96603505 0.90652108 0.20081835 0.08273265 0.35839982]
 [0.95329266 0.26706319 0.65799325 0.98379384 0.9606134 ]
 [0.54710852 0.37965726 0.60023    0.8205887  0.08900703]]
[[9 2 8 0 6]
 [8 5 2 1 4]
 [2 2 2 6 3]
 [3 2 8 6 2]
 [3 7 7 7 3]]


In [8]:
zeros = np.zeros((4,5))
ones = np.ones((4,5)) 
empty = np.empty((4,5))
print("4x5 matrix with zero\n",zeros)
print("4x5 matrix with one\n",ones)
print("4x5 matrix with empty\n",empty)  

4x5 matrix with zero
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
4x5 matrix with one
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
4x5 matrix with empty
 [[6.94630157e-310 4.68367412e-310 6.94628410e-310 6.94628410e-310
  6.94628411e-310]
 [6.94628411e-310 6.94628411e-310 6.94628411e-310 6.94628411e-310
  6.94628411e-310]
 [6.94628411e-310 6.94628411e-310 6.94628411e-310 6.94628411e-310
  6.94628411e-310]
 [6.94628411e-310 7.11454530e-322 1.58101007e-322 4.68367405e-310
  6.94628411e-310]]


In [10]:
# using arange function to create an array
arange = np.arange(0,10,2)
print("create a array of 0 to 10 with step 2\n",arange)

create a array of 0 to 10 with step 2
 [0 2 4 6 8]


In [13]:
# using linspace function to create an array
linspace = np.linspace(0,10,5)
print("create a array of 0 to 10 with 5 elements\n",linspace)
x = np.linspace(0,2*np.pi,100)
f = np.sin(x)
print(f)

create a array of 0 to 10 with 5 elements
 [ 0.   2.5  5.   7.5 10. ]
[ 0.00000000e+00  6.34239197e-02  1.26592454e-01  1.89251244e-01
  2.51147987e-01  3.12033446e-01  3.71662456e-01  4.29794912e-01
  4.86196736e-01  5.40640817e-01  5.92907929e-01  6.42787610e-01
  6.90079011e-01  7.34591709e-01  7.76146464e-01  8.14575952e-01
  8.49725430e-01  8.81453363e-01  9.09631995e-01  9.34147860e-01
  9.54902241e-01  9.71811568e-01  9.84807753e-01  9.93838464e-01
  9.98867339e-01  9.99874128e-01  9.96854776e-01  9.89821442e-01
  9.78802446e-01  9.63842159e-01  9.45000819e-01  9.22354294e-01
  8.95993774e-01  8.66025404e-01  8.32569855e-01  7.95761841e-01
  7.55749574e-01  7.12694171e-01  6.66769001e-01  6.18158986e-01
  5.67059864e-01  5.13677392e-01  4.58226522e-01  4.00930535e-01
  3.42020143e-01  2.81732557e-01  2.20310533e-01  1.58001396e-01
  9.50560433e-02  3.17279335e-02 -3.17279335e-02 -9.50560433e-02
 -1.58001396e-01 -2.20310533e-01 -2.81732557e-01 -3.42020143e-01
 -4.00930535e-01 -4.

### Basic NumPy Operations

In [17]:
a = np.array([5,5,7,8,4,7])
b = np.array([1,2,3,4,5,6])
add = a+b
print("Summation of a and b array is ", add)
sub = a-b
print("Subtraction of a and b array is ", sub)
mul = a*b
print("Multiplication of a and b array is ", mul)
div = a/b
print("Division of a and b array is ", div)

# bolean array
bool = a > b
print("Boolean array is ", bool)

Summation of a and b array is  [ 6  7 10 12  9 13]
Subtraction of a and b array is  [ 4  3  4  4 -1  1]
Multiplication of a and b array is  [ 5 10 21 32 20 42]
Division of a and b array is  [5.         2.5        2.33333333 2.         0.8        1.16666667]
Boolean array is  [ True  True  True  True False  True]


In [18]:
#  matrix product
mat_pod = a @ b
print("Matrix product is ", mat_pod)

Matrix product is  130


In [20]:
a.dot(b)

130

In [27]:
# statistical analysis
c = np.array([5,2,3,9,5,5,7,2,9,10]).reshape(5,2)
c

array([[ 5,  2],
       [ 3,  9],
       [ 5,  5],
       [ 7,  2],
       [ 9, 10]])

In [29]:
c.min()

2

In [30]:
c.min(axis=0)

array([3, 2])

In [31]:
# sum of all elements in the array
c.sum()

57

In [32]:
c.sum(axis=0)

array([29, 28])

In [33]:
# cumulative sum of all elements in the array
c.cumsum()

array([ 5,  7, 10, 19, 24, 29, 36, 38, 47, 57])